### ISSUE TITLE
bad request with spaces

### ISSUE THREAD

**Issue by britofilipe7** [krzych82/api-client-python3#1]
Hello,

After testing the code with a 'SymbolList[0]' containing a space it return bad request, for example test with "NEB/J 25". I tried to use urllib.parse.quote instead of urllib.parse.urlencode, for replacing the spaces with a '%20', but it didn't solve.

The code works well with other symbols like '.', '/', etc...

**Comment by krzych82** [comment]
NEB/J 25 is not a valid symbol. 
It is manufacturer part number, but TME Api works with TME symbols (NEB/J25)
https://www.tme.eu/en/details/neb_j25/dc-power-connectors/lumberg/neb-j-25/

**Comment by britofilipe7** [comment]
Hi,

thank you for the response.
But it works in the TME sandbox, I'm using the same parameters "/Products/Search", please check bellow.

![image](https://user-images.githubusercontent.com/83494402/178839877-bcc20155-8f99-4fe0-8ced-bc011ef5fe2d.png)

**Comment by krzych82** [comment]
It should by ok now
