### ISSUE TITLE
Please consider adding a license

### ISSUE THREAD

**Issue by spike77453** [krzych82/api-client-python3#3]
Hi @krzych82,

Thanks a bunch for creating this python module. Would you consider adding a license, ideally one that would allow a downstream project such as https://github.com/sparkmicro/Ki-nTree (see [115](https://github.com/sparkmicro/Ki-nTree/pull/115) and [164](https://github.com/sparkmicro/Ki-nTree/pull/164) for details) to use your source code?

Cheers!

**Comment by krzych82** [comment]
Hi @spike77453,
License added. Feel free to use this software.
